# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "01042f00ae8bb522a9c03d3e7e1910318208a2c9fbdd23a6315577a9c98553a8"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
engines:
    - name: bing
      disabled: false
    - name : baidu
      engine : json_engine
      paging : True
      first_page_num : 0
      search_url : https://www.baidu.com/s?tn=json&wd={query}&pn={pageno}&rn=50
      url_query : url
      title_query : title
      content_query : abs
      categories : general
search:
    formats:
        - html
        - json
